version: '3.3'

services:
  graph:
    image: node:${NODE_VERSION}
    working_dir: "/app"
    networks: 
      - web
    env_file: .env
    environment: 
      - "NODE_ENV=${ENVIRONMENT}"
      - "HOSTNAME=${HOST}"
    volumes:
      - ./src:/app
    restart: unless-stopped
    command: bash -c "yarn && yarn run prepare && yarn run start"
    labels:
      - "traefik.frontend.rule=Host:${HOST};PathPrefix:/graphql,/socket"
      - "traefik.port=4000"
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.tags=${HOST}"
networks: 
  web:
    external: true
